### ISSUE TITLE
How to run inference with input of different dtypes?

### ISSUE THREAD

**Issue by HaoboGu** [nbigaouette/onnxruntime-rs#92]
Hello, I'm trying to run a model which has the following input: 
```rust
println!("input format: {:?}", &session.inputs);

input format: [Input { name: "input_ids", input_type: Int64, dimensions: [None, None] }, Input { name: "past_0", input_type: Float, dimensions: [Some(2), None, Some(6), None, Some(64)] }]
```

I tried to build two arrays, with i64 and f32 dtype, but I cannot put them in a vector which can be fed to `session.run`

```rust
let input_array = ArrayD::<i64>::from_shape_vec(IxDyn(&[1, context_len]), ids).unwrap();
let past1_array = ArrayD::<f32>::from_shape_vec(IxDyn(&[2, 1, 6, 0, 64]), vec![]).unwrap();
session.run(vec![input_array, past1_array];
```

it cannot compile:
```
session.run(vec![input_array, past1_array];
                              ^^^^^^^^^^^ expected `i64`, found `f32`
```

Anyone has idea about it? Thanks

**Comment by rmarrugat** [comment]
Current `run` implementation just accepts a `input_arrays: Vec<Array<TIn, D>>` instead of something like `input_arrays: Vec<Array<Box<TIn>, D>>` which would allow the flexibility you are seeking.

I would recommend you to fork the repository and implement a variation of the `Session::run` function that accepts inputs of different types.

**Comment by HaoboGu** [comment]
@rmarrugat Thank you, I'll have a try
